theme = "hyde"
baseurl = "/"
languageCode = "en-us"
title = "Casual Inference"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    # description = ""
    # Change contactHeader text
    # Or comment out to use <hr> instead
    # contactHeader = "Contact"

    # Change Hyde theme
    # themeColor = "theme-base-08"
    # Overide or add custom CSS styles
    # customCSS = "/css/custom.css"
    
    # Reverse layout
    # layoutReverse = true
    
    # Show full blog post
    truncate = false
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"